### ISSUE TITLE
Kex push-api subscription with aws-iot-device-sdk-java

### ISSUE THREAD

**Issue by davidSanchezEmpaua** [europace/kex-push#3]
Hi,
I’m using the Java SDK _https://github.com/aws/aws-iot-device-sdk-java#use-the-sdk_ to subscribe to the AWS IoT topics. I’m expecting to receive the events with a Json payload.

My program seems to be connecting correctly but I’m not receiving any events.

One thing is that I was provided with a public key, but do not see where it should be used.

Below is a sample of the code:

`String clientEndpoint = "aneo2a8he66vc-ats.iot.eu-central-1.amazonaws.com"

String clientId = "the-clientid-provided"

String certificateFile = "certificate_file.txt";               // A file containing the certificate provided

String String privateKeyFile = "privateKey_file.txt"  // A file containing the private key provided

KeyStorePasswordPair pair = SampleUtil.getKeyStorePasswordPair(certificateFile, privateKeyFile, algorithm);

awsIotClient = new AWSIotMqttClient(clientEndpoint, clientId, pair.keyStore, pair.keyPassword);
awsIotClient.connect();

// Also tried: "PROD_TESTUMGEBUNG/VGD43/JUK74/AJX43/MVB90/Vertriebe/Dr.klein/Testvertrieb"

AWSIotTopic topic = new TestTopicListener("PROD_TESTUMGEBUNG/VGD43/JUK74/AJX43/MVB90", AWSIotQos.QOS0); 

awsIotClient.subscribe(topic, true);
`

**Comment by SpinGit** [comment]
@davidSanchezEmpaua Which vorgang did you try? (vorgangsnummer)

// Also tried: "PROD_TESTUMGEBUNG/VGD43/JUK74/AJX43/MVB90/Vertriebe/Dr.klein/Testvertrieb" -> /Vertriebe/Dr.klein/Testvertrieb are not valid partnerIds.

We need your current vorgangsnummer.

**Comment by davidSanchezEmpaua** [comment]
Thanks for you reply.

I'm following these instructions that we were given to us:

1. Subscribe via "endpoint": "aneo2a8he66vc-ats.iot.eu-central-1.amazonaws.com"
2. Filter the processes via the topic: "topic": ""PROD_TESTUMGEBUNG/VGD43/JUK74/AJX43/MVB90”, (Europace)/Vertriebe/Dr.klein/Testvertrieb)
3. partnerId and thingName do not matter
4. clientId is needed for the connection to AWS
5. certificate + public Key is the gate to subscribe
6. certificate.keyPair.privateKey is for transport protection from https direction AWS

The other information that we were given is: PartnerId, thingName, clientId, certificate and keyPair (private & public).

The instructions provided do not mention a "vorgangsnummer" and they say that the "partnerId" does not matter.

I'm also a bit confused by step 5 of the instructions  (certificate + public Key is the gate to subscribe). I could not find anywhere in the SDK where I could provide the public key.

**Comment by SpinGit** [comment]
Hello David,

i implemented a reference implementation and it works fine.

You have to use the `certificatePem` and the `privateKey`.

My env properties:
```
clientEndpoint: {clientEndpoint}

clientId: {clientId}

certificateFile: /Users/stephan.malek/Europace/Services/service-template/template-service/src/main/resources/cert.pem

privateKeyFile: /Users/stephan.malek/Europace/Services/service-template/template-service/src/main/resources/private.pem

keyAlgorithm: RSA
```

As `topicName` you have to use: `String topicName = "PROD_TESTUMGEBUNG/VGD43/JUK74/AJX43/MVB90/#";`

When your subscribe is succesfull and you change a value in a Kreditsmart Vorgang (https://www.europace2.de/kreditsmart/?vorgangsnummer=NC7XQ6), then you get a publish message.

```
public class MyTopic extends AWSIotTopic {
  public MyTopic(String topic, AWSIotQos qos) {
    super(topic, qos);
  }

  @Override
  public void onMessage(AWSIotMessage message) {
    new String(message.payload)
  }
}
```

**Comment by SpinGit** [comment]
@davidSanchezEmpaua Do you need help anymore? Otherwise i would like to close this issue.

**Comment by davidSanchezEmpaua** [comment]
Thanks for your help. I'm getting the events by changing the topic as you suggested.

I'm closing the issue.
